#!/usr/bin/env ruby

print "Enter Service Name: "
serviceName = gets.chomp
serviceFileName = serviceName.downcase
serviceClassName = serviceName.split('_').map(&:capitalize).join


def downcase_first_letter(str)
    str[0].downcase + str[1..]
end
serviceVariableName = downcase_first_letter(serviceClassName)

#SERVICE
serviceClassInitializer = 
%W[
'''
abstract class #{serviceClassName}DataSource { \n } \n \n
abstract class #{serviceClassName}ServiceInterface { \n } \n \n
class #{serviceClassName}Service implements 
#{serviceClassName}DataSource , #{serviceClassName}ServiceInterface { \n
}
'''
].join(' ')
#END PRESENTATION

#UNIT TEST
getTestMode = '''Get.testMode = true;'''

unitTestInitializer = '''test("sut = system under test ", () async { });'''

serviceTestClassInitializer = 
%W[
'''
import "../../../lib/services/#{serviceFileName}/#{serviceFileName}_service.dart"; \n
import "package:flutter_test/flutter_test.dart"; \n
import "package:get/get.dart"; \n \n
void main(){ \n
#{getTestMode} \n
var sut = #{serviceClassName}Service();\n
#{unitTestInitializer} \n
}
'''
].join(' ')

#END UNIT TEST

if serviceName.length > 1

    back = "\ && cd .. "
    #Service
	createService = 
            "cd lib" + 
            "\ && cd services" +
            "\ && mkdir " + serviceFileName + 
            "\ && cd " + serviceFileName +
            "\ && mkdir requests" +
            "\ && mkdir response" +
            "\ && touch " + serviceFileName + "_service.dart" +
            "\ && tee " + serviceFileName + "_service.dart <<< " + serviceClassInitializer
    # End Service

    # Unit Test
	createServiceTest = 
            "\ && cd test" + 
            "\ && cd services" +
            "\ && mkdir " + serviceFileName + 
            "\ && cd " + serviceFileName +
            "\ && touch " + serviceFileName + "_service_test.dart" +
            "\ && tee " + serviceFileName + "_service_test.dart <<< " + serviceTestClassInitializer
    # End Unit Test


	exec(
    createService +
    back + 
    back + 
    back + 
    createServiceTest
	)
else
	puts "Please enter Presentation Name name!"
end
