#!/usr/bin/env ruby

print "Enter Project Name: "
projectName = gets.chomp

settingsJson = 
%W[
'''
{\n
\t"java.configuration.updateBuildConfiguration": "interactive", \n
\t"[dart]": { \n
\t\t"editor.defaultFormatter": "Dart-Code.dart-code", \n
\t\t"editor.formatOnSave": true, \n
\t} \n
}\n
'''
].join()

if projectName.length > 1
	createProject = "flutter create " + projectName + 
		"&& cd " + projectName + 
		"&& touch sonar.properties" +
		"&& flutter pub add get" +
		"&& flutter pub add dio" + 
#vscode
		"&& mkdir .vscode" +
		"&& cd .vscode" +
		"\ && touch " + "settings.json" +
		"\ && tee " + "settings.json <<< " + settingsJson +
		"&& cd .."
#vscode
	
	createStructureComponents = 
		"&& mkdir assets" +
		"&& mkdir base" +
		"&& cd base" +
		"&& mkdir dependencies" +
		"&& cd .." +
		"&& mkdir presentation" +
		"&& mkdir network" +
		"&& mkdir storage" +
		"&& mkdir services" +
		"&& mkdir ui-components" +
		"&& cd .."

	createStructure = "&& cd lib" + createStructureComponents
	
	createStructureTest = "&& cd test" + createStructureComponents

	createExample = 
		"&& cd lib" +
		"&& cd presentation" +
		"&& mkdir example" +
		"&& cd example" +
		"&& mkdir constants" +
		"&& cd constants" +
		"&& touch example_constants.dart" +
		"&& cd .." +
		"&& mkdir controller" +
		"&& cd controller" +
		"&& touch example_controller.dart" +
		"&& touch example_binding.dart" +
		"&& cd .." +
		"&& mkdir view" +
		"&& cd view" +
		"&& touch example_page.dart" +
		"&& cd .." +
		"&& mkdir model" +
		"&& cd model" +
		"&& touch example_viewmodel.dart" +
		"&& touch example_model.dart" +
		"&& touch example_enum.dart" +
		"&& cd .." +
		"&& mkdir service" +
		"&& cd service" +
		"&& touch example_service.dart" +
		"&& cd .."


	exec(
	createProject +
	createStructure +
	createStructureTest +
	createExample
	)
else
	puts "Please enter project name!"
end
