#!/usr/bin/env ruby

print "Enter Dependency Name: "
dependencyName = gets.chomp
dependencyFileName = dependencyName.downcase
dependencyClassName = dependencyName.split('_').map(&:capitalize).join


#SERVICE
dependencyClassInitializer = 
%W[
'''
abstract class #{dependencyClassName}DependencySource { \n } \n \n
abstract class #{dependencyClassName}DependencyInterface { \n } \n \n
class #{dependencyClassName}Dependency implements 
#{dependencyClassName}DependencySource , #{dependencyClassName}DependencyInterface { \n
}
'''
].join(' ')
#END PRESENTATION


#UNIT TEST
getTestMode = '''Get.testMode = true;'''

unitTestInitializer = '''test("sut = system under test ", () async { });'''

dependencyTestClassInitializer = 
%W[
'''
import "../../../../lib/base/dependencies/#{dependencyFileName}/#{dependencyFileName}_dependency.dart"; \n
import "package:flutter_test/flutter_test.dart"; \n
import "package:get/get.dart"; \n \n
void main(){ \n
#{getTestMode} \n
var sut = #{dependencyClassName}Dependency();\n
#{unitTestInitializer} \n
}
'''
].join(' ')

#END UNIT TEST


if dependencyName.length > 1

    back = "\ && cd .. "
    #Service
	createDependency = 
            "cd lib" + 
            "\ && cd base" +
            "\ && cd dependencies" +
            "\ && mkdir " + dependencyFileName + 
            "\ && cd " + dependencyFileName +
            "\ && touch " + dependencyFileName + "_dependency.dart" +
            "\ && tee " + dependencyFileName + "_dependency.dart <<< " + dependencyClassInitializer
    # End Service

     # Unit Test
	createDependencyTest = 
    "\ && cd test" + 
    "\ && cd base" + 
    "\ && cd dependencies" +
    "\ && mkdir " + dependencyFileName + 
    "\ && cd " + dependencyFileName +
    "\ && touch " + dependencyFileName + "_dependency_test.dart" +
    "\ && tee " + dependencyFileName + "_dependency_test.dart <<< " + dependencyTestClassInitializer
    # End Unit Test

	exec(
    createDependency +
    back + 
    back +
    back +
    back +
    createDependencyTest
	)
else
	puts "Please enter Dependency Name!"
end
