#!/usr/bin/env ruby

print "Enter Presentation Name: "
presentationName = gets.chomp

#PRESENTATION
constantClassInitializer = 
%W[
'''
import "package:get/get.dart"; \n
class #{presentationName.capitalize}Constant { \n

}
'''
].join(' ')

controllerBindingInitializer = 
%W[
'''
import "../service/#{presentationName.downcase}_service.dart"; \n
import "#{presentationName.downcase}_controller.dart"; \n
import "package:get/get.dart"; \n \n
class #{presentationName.capitalize}Binding extends Bindings { \n
@override \n
void dependencies() { \n
 #{presentationName.capitalize}Service #{presentationName.downcase}Service = #{presentationName.capitalize}Service(); \n

  #{presentationName.capitalize}ControllerInterface controller = #{presentationName.capitalize}Controller(
      #{presentationName.downcase}Service: #{presentationName.downcase}Service,
    ) as #{presentationName.capitalize}ControllerInterface; \n
    \n
    Get.put(controller);
}\n
}
'''
].join(' ')

controllerClassInitializer = 
%W[
'''
import "../service/#{presentationName.downcase}_service.dart"; \n
import "../model/#{presentationName.downcase}_viewmodel.dart"; \n
import "package:get/get.dart"; \n \n
abstract class #{presentationName.capitalize}ControllerRepository { \n 
    late final #{presentationName.capitalize}ServiceInterface #{presentationName.downcase}Service; \n
} \n \n
abstract class #{presentationName.capitalize}ControllerInterface { \n 
    late #{presentationName.capitalize}ViewModel viewModel; \n
} \n \n
class #{presentationName.capitalize}Controller extends GetxController implements 
#{presentationName.capitalize}ControllerRepository , #{presentationName.capitalize}ControllerInterface { \n
\n
      @override \n
  var viewModel = #{presentationName.capitalize}ViewModel(); \n
\n
    @override \n
  late final #{presentationName.capitalize}ServiceInterface #{presentationName.downcase}Service; \n
\n
  #{presentationName.capitalize}Controller({ \n
    required this.#{presentationName.downcase}Service, \n
  }); \n
}
'''
].join(' ')

viewClassInitializer = 
%W[
'''
import "package:flutter/material.dart"; \n
import "package:get/get.dart"; \n 
import "../controller/#{presentationName.downcase}_controller.dart"; \n \n
class #{presentationName.capitalize}Page extends GetView<#{presentationName.capitalize}ControllerInterface> { \n
\n
static const String routeName = "/#{presentationName.downcase}-page"; \n
\n
const #{presentationName.capitalize}Page({ \n
super.key, \n
}); \n
\n
@override \n
Widget build(BuildContext context) {\n
return Container();
}\n
}
'''
].join(' ')

modelClassInitializer =
%W[
'''
import "package:get/get.dart"; \n \n
class #{presentationName.capitalize}ViewModel { \n
    Rx<String> title = "''".obs; \n
}
'''
].join(' ')

serviceClassInitializer = 
%W[
'''
import "package:get/get.dart"; \n \n
abstract class #{presentationName.capitalize}ServiceRepository { \n } \n \n
abstract class #{presentationName.capitalize}ServiceInterface { \n } \n \n
class #{presentationName.capitalize}Service implements 
#{presentationName.capitalize}ServiceRepository , #{presentationName.capitalize}ServiceInterface { \n
}
'''
].join(' ')
#END PRESENTATION

#UNIT TEST
getTestMode = '''Get.testMode = true;'''

unitTestInitializer = '''test("sut = system under test ", () async { });'''


constantTestClassInitializer = 
%W[
'''
import "../../../../lib/presentation/#{presentationName.downcase}/constants/#{presentationName.downcase}_constant.dart"; \n
import "package:flutter_test/flutter_test.dart"; \n
import "package:get/get.dart"; \n \n
void main(){ \n
#{getTestMode} \n
var sut = #{presentationName.capitalize}Constant();\n
#{unitTestInitializer} \n
}
'''
].join(' ')

controllerTestBindingInitializer =  
%W[
'''
import "../../../../lib/presentation/#{presentationName.downcase}/controller/#{presentationName.downcase}_binding.dart"; \n
import "package:flutter_test/flutter_test.dart"; \n
import "package:get/get.dart"; \n \n
void main(){ \n
#{getTestMode} \n
var sut = #{presentationName.capitalize}Binding();\n
#{unitTestInitializer} \n
}
'''
].join(' ')


controllerTestClassInitializer = 
%W[
'''
import "../../../../lib/presentation/#{presentationName.downcase}/controller/#{presentationName.downcase}_controller.dart"; \n
import "package:flutter_test/flutter_test.dart"; \n
import "package:get/get.dart"; \n \n
void main(){ \n
#{getTestMode} \n
var sut = #{presentationName.capitalize}Controller();\n
#{unitTestInitializer} \n
}
'''
].join(' ')


serviceTestClassInitializer = 
%W[
'''
import "../../../../lib/presentation/#{presentationName.downcase}/service/#{presentationName.downcase}_service.dart"; \n
import "package:flutter_test/flutter_test.dart"; \n
import "package:get/get.dart"; \n \n
void main(){ \n
#{getTestMode} \n
var sut = #{presentationName.capitalize}Service();\n
#{unitTestInitializer} \n
}
'''
].join(' ')

#END UNIT TEST

if presentationName.length > 1

    #Presentation
	createPresentation = 
            "cd lib" + 
            "\ && cd presentation" +
            "\ && mkdir " + presentationName.downcase + 
            "\ && cd " + presentationName.downcase

    createConstant = 
            "\ && mkdir constants" +
            "\ && cd constants" +
            "\ && touch " + presentationName.downcase + "_constant.dart" +
            "\ && tee " + presentationName.downcase + "_constant.dart <<< " + constantClassInitializer

    createController = 
            "\ && mkdir controller" +
            " && cd controller" +
            "\ && touch " + presentationName.downcase + "_binding.dart" +
            "\ && tee " + presentationName.downcase + "_binding.dart <<< " + controllerBindingInitializer +
            " && touch " + presentationName.downcase + "_controller.dart" +
            " && tee " + presentationName.downcase + "_controller.dart <<< " + controllerClassInitializer
    
    createView =
            "\ && mkdir view" +
            "\ && cd view" +
            "\ && touch " + presentationName.downcase + "_page.dart" +
            "\ && tee " + presentationName.downcase + "_page.dart <<< " + viewClassInitializer

    createViewModel = 
            "\ && mkdir model" +
            "\ && cd model" +
            "\ && touch " + presentationName.downcase + "_viewmodel.dart" +
            "\ && tee " + presentationName.downcase + "_viewmodel.dart <<< " + modelClassInitializer

    createService = 
            "\ && mkdir service" +
            "\ && cd service" +
            "\ && touch " + presentationName.downcase + "_service.dart" +
            "\ && tee " + presentationName.downcase + "_service.dart <<< " + serviceClassInitializer
    # EndPresentation

    back = "\ && cd .. "
    
	createPresentationTest = 
            "\ && cd test" + 
            "\ && cd presentation" +
            "\ && mkdir " + presentationName.downcase + 
            "\ && cd " + presentationName.downcase
    createConstantTest = 
        "\ && mkdir constants" +
        "\ && cd constants" +
        "\ && touch " + presentationName.downcase + "_constant_test.dart" +
        "\ && tee " + presentationName.downcase + "_constant_test.dart <<< " + constantTestClassInitializer

    createControllerTest = 
        "\ && mkdir controller" +
        "\ && cd controller" +
        "\ && touch " + presentationName.downcase + "_binding_test.dart" +
        "\ && tee " + presentationName.downcase + "_binding_test.dart <<< " + controllerTestBindingInitializer +
        "\ && touch " + presentationName.downcase + "_controller_test.dart" +
        "\ && tee " + presentationName.downcase + "_controller_test.dart <<< " + controllerTestClassInitializer
    
    createServiceTest = 
        "\ && mkdir service" +
        "\ && cd service" +
        "\ && touch " + presentationName.downcase + "_service_test.dart" +
        "\ && tee " + presentationName.downcase + "_service_test.dart <<< " + serviceTestClassInitializer


	exec(
	createPresentation + 
    createConstant +
    back +
    createController +
    back +
    createView +
    back +
    createViewModel +
    back +
    createService +
    back +
    back +
    back +
    back +
    createPresentationTest +
    createConstantTest +
    back +
    createControllerTest +
    back +
    createServiceTest
	)
else
	puts "Please enter Presentation Name name!"
end
